/* EBA Fraud Taxonomy v7.0: names and codes, generated from taxonomy.json by extension/build_data.py. Do not edit by hand. Taxonomy content: Euro Banking Association (CC BY 4.0). */
globalThis.EBA_TAXONOMY = {
 "taxonomy": "EBA Fraud Taxonomy",
 "version": "7.0",
 "published": "2026-06-03",
 "effective": "2027-01-01",
 "publisher": "Euro Banking Association (EBA)",
 "licence": "CC BY 4.0",
 "sha": "d0eac72bd6a6",
 "dims": [
  "method",
  "modus",
  "initiator",
  "instrument",
  "labels"
 ],
 "multi": [
  "labels"
 ],
 "newModus": "New fraud type (describe)",
 "codes": {
  "method": {
   "Brute force": "T0001",
   "Data breach / theft": "T0002",
   "Email contact": "T0004",
   "Fake advertising": "T0005",
   "Fake merchant": "T0006",
   "In person contact": "T0007",
   "Malware": "T0008",
   "Online contact": "T0010",
   "Phone contact": "T0011",
   "Physical copy": "T0012",
   "Physical theft": "T0013",
   "Social media contact": "T0015",
   "Text message contact": "T0016",
   "New method": "T0017"
  },
  "modus": {
   "Safe account fraud": "T0019",
   "Stop unauthorised transaction fraud": "T0020",
   "Stop unauthorised access fraud": "T0105",
   "Advance fee fraud": "T0022",
   "Claim a benefit fraud": "T0106",
   "Investment fraud": "T0023",
   "Online shopping fraud": "T0025",
   "Support a friend or family member fraud": "T0121",
   "Romance fraud": "T0095",
   "Charity / donation fraud": "T0122",
   "Extortion": "T0029",
   "Impersonation of creditor": "T0031",
   "Impersonation of person with authority to instruct payments": "T0117",
   "Overpayment fraud": "T0033",
   "Phoney debt/bill collection": "T0034",
   "Fake institution": "T0036",
   "Pure account takeover": "T0038",
   "Creditor account data manipulation": "T0039",
   "Control of card or card details by unauthorised party": "T0110",
   "Fraudulent card application": "T0045",
   "Fraudulent card claim": "T0046",
   "Fraudulent use of cash back scheme": "T0047",
   "Other first party fraud": "T0112",
   "New fraud type (describe)": "T0048"
  },
  "initiator": {
   "Customer": "T0049",
   "Fraudster": "T0050",
   "First party": "T0051"
  },
  "instrument": {
   "Account-to-account transaction": "T0115",
   "Card payment": "T0116"
  },
  "labels": {
   "Account takeover": "T0052",
   "Advanced persistent threat (APT)": "T0053",
   "Beneficiary account change": "T0054",
   "BIN attack": "T0055",
   "Card chip relay": "T0123",
   "Card details stolen": "T0041",
   "Card lost": "T0113",
   "Card never received": "T0043",
   "Card not present": "T0056",
   "Card peeking": "T0057",
   "Card present": "T0058",
   "Card skimming": "T0059",
   "Card stolen": "T0114",
   "CEO fraud": "T0060",
   "Collusive merchant / data misuse": "T0061",
   "Contactless relay fraud": "T0062",
   "Credit master": "T0063",
   "Discount / refund fraud": "T0107",
   "Email compromise": "T0003",
   "Exploiting the system": "T0064",
   "Fake bank / financial institution": "T0065",
   "Fake betting": "T0066",
   "Fake customer support": "T0067",
   "Fake loan": "T0068",
   "Fake police": "T0069",
   "Fake prize, sweepstakes, and lottery fraud": "T0108",
   "Fake website": "T0070",
   "False billing fraud": "T0071",
   "Falsified ID": "T0072",
   "Falsifying personal and financial information": "T0073",
   "Family emergency": "T0118",
   "Fraudulent MOTO card transaction": "T0075",
   "Fraudulent use of Contract for Difference (CFD)": "T0076",
   "Fraudulent use of crypto currency": "T0077",
   "Gift card": "T0078",
   "Goods not received": "T0079",
   "Impersonation": "T0080",
   "Keylogger": "T0081",
   "Lookalike domain": "T0082",
   "Malware – MageCart": "T0083",
   "Manipulated invoice": "T0084",
   "Money muling": "T0124",
   "Money mule victim": "T0125",
   "Multiple imprint": "T0085",
   "Nigeria": "T0086",
   "Nightclub": "T0087",
   "Non-crypto investment fraud": "T0109",
   "No physical meeting": "T0088",
   "Phishing": "T0089",
   "Physical meeting": "T0090",
   "Physical proximity credential theft / known perpetrator": "T0091",
   "Physical proximity credential theft / unknown perpetrator": "T0092",
   "Ransomware": "T0093",
   "Remote access trojan": "T0094",
   "Sextortion": "T0096",
   "Shock calls": "T0119",
   "Shoulder surfing": "T0097",
   "Smishing": "T0098",
   "Social media compromise": "T0014",
   "Spoofed email": "T0120",
   "Subscription fraud": "T0099",
   "Synthetic ID": "T0100",
   "Third-party channel": "T0101",
   "Third-party vendor account takeover": "T0102",
   "Use of counterfeit cards": "T0044",
   "Vishing": "T0103",
   "Wecycle": "T0104"
  }
 },
 "hlcOf": {
  "Safe account fraud": "Your money / personal information is at risk",
  "Stop unauthorised transaction fraud": "Your money / personal information is at risk",
  "Stop unauthorised access fraud": "Your money / personal information is at risk",
  "Advance fee fraud": "You can earn/save a lot of money",
  "Claim a benefit fraud": "You can earn/save a lot of money",
  "Investment fraud": "You can earn/save a lot of money",
  "Online shopping fraud": "I am a seller/buyer",
  "Support a friend or family member fraud": "Please help",
  "Romance fraud": "Please help",
  "Charity / donation fraud": "Please help",
  "Extortion": "Send me money or I’ll …",
  "Impersonation of creditor": "We’ve changed account number",
  "Impersonation of person with authority to instruct payments": "Comply with payment obligation",
  "Overpayment fraud": "Comply with payment obligation",
  "Phoney debt/bill collection": "Comply with payment obligation",
  "Fake institution": "Can you please sign in / sign this off?",
  "Pure account takeover": "Account / card / card details / digital wallet takeover by unauthorised party",
  "Creditor account data manipulation": "Account / card / card details / digital wallet takeover by unauthorised party",
  "Control of card or card details by unauthorised party": "Account / card / card details / digital wallet takeover by unauthorised party",
  "Fraudulent card application": "First party fraud",
  "Fraudulent card claim": "First party fraud",
  "Fraudulent use of cash back scheme": "First party fraud",
  "Other first party fraud": "First party fraud",
  "New fraud type (describe)": "Not covered by the taxonomy"
 }
};
